default: &default
  url: <%= ENV['LOFOCATS_API_URL'] || 'http://localhost:3001' %>
  version: <%= ENV['LOFOCATS_API_VERSION'] || '1' %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
